### ISSUE TITLE
update_positions requires Ncomponents > 1

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyradiosky#171]
The lmn calculation of `update_positions` (lines 2226-2228 in the main branch of skymodel.py) seem hardcoded for there to exist a component axis of length > 1.  The method errors if there is only one component in the skymodel.

**Comment by aelanman** [comment]
It looks like this error hasn't come up before because on line 676 any input longitude/latitude are made `np.atleast_1d` before being assigned as attributes. Doing this, we force all coordinates to be list. If we want to make this the default behavior, it might make sense to give the lon/lat UVParameters a setter function that runs `atleast_1d` on the inputs to ensure any assigned values are compliant.

For now, I believe this can be fixed by replacing the colons in lines 2226 -- 2228 with ellipses:
```
        pos_l = np.sin(alt_az[1, ...]) * np.cos(alt_az[0, ...])
        pos_m = np.cos(alt_az[1, ...]) * np.cos(alt_az[0, ...])
        pos_n = np.sin(alt_az[0, ...])
```

Also, line 2236 needs to be replaced as follows:
```
        self.above_horizon = self.alt_az[0] > 0.0
```

I haven't pushed the changes yet because I haven't fully tested them, but this should handle both scalar and non-scalar source lists appropriately.

**Comment by StellanBechtold** [comment]
This is a reduced version of the code I have been running that was giving me the error regarding the size of the arrays for calculating lmn.
```
import pyradiosky
import numpy as np
from astropy.coordinates import (EarthLocation, Latitude, Longitude, SkyCoord)
from astropy.time import Time
sm = pyradiosky.SkyModel()
sm.ra = Longitude(45, unit='deg')
sm.dec = Latitude(45, unit='deg')
sm.update_positions(Time(2458000, format='jd'), EarthLocation(1,1,1))
```

**Comment by bhazelton** [comment]
Thanks for reporting this @StellanBechtold. Can you try running the check method `sm.check()` before you call `update_positions`? That method checks to see if you have a properly defined SkyModel object. I think there might be a problem with the way the object is defined that causes this. If so, I think the fix is maybe to call the check method at the beginning of this method.

**Comment by jpober** [comment]
@StellanBechtold can you post your solution to this issue?  If I recall, things were fixed by setting your single number values (like sm.ra) to length one vectors (as well as setting a couple of unrelated but necessary keywords).  So it seems like there isn't a bug in the code but that we could better handle instances of single source SkyModels.

**Comment by jpober** [comment]
@StellanBechtold We talked about this a bit today and think the __init__ method should be able to do what you want and not require you to go changing the shape of any length-1 arrays etc.  Can you try creating your SkyModel via that method and see that it passes the check?  If so, we can close this issue.

**Comment by StellanBechtold** [comment]
Using the `__init__` method appears to solve the issue. Manually changing the shape of the arrays also worked, but `__init__` is much cleaner. For posterity, this is how I implemented the code that gave no errors.

```
import pyradiosky
from astropy.coordinates import (Longitude,Latitude)
from astropy.units import Quantity
sm = pyradiosky.SkyModel(name = 'source', ra = Longitude(180, unit = 'deg'), dec = Latitude(65, unit = 'deg'), stokes = Quantity([1,0,0,0], unit = ' Jy'), spectral_type = 'flat')
```
`sm.check()` returns True. So, I believe we can close the issue. Thank you for all the help.

**Comment by jpober** [comment]
Ok, great.  I will go ahead and close.
