### ISSUE TITLE
Unused parameters

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyradiosky#89]
https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/ef9ca0bfe4411b8a2cd9b2d21a76bcef9bc747d8/pyradiosky/skymodel.py#L178

There are three unused parameters in the __init__ of `SkyModel` (`pos_tol`, `extended_model_group` and `beam_amp`). Is this intentional?

**Comment by bhazelton** [comment]
No, it's not intentional and it's a bad problem (at least for `extended_model_group` and `beam_amp`) @rlbyrne  this means that even though they're being read by the `read_fhd_catalog` method they aren't being set on the object. I'll make a PR to fix this shortly.

I'm not quite sure what `pos_tol` is meant to be used for, it's no where else in the pyradiosky repo. @aelanman do you know?

**Comment by aelanman** [comment]
That was used in the __eq__ method as the tolerance for allclose comparisons of angles, back when SkyModel was in pyuvsim. It should definitely go.

**Comment by bhazelton** [comment]
fixed in #93
